### ISSUE TITLE
I'd like an option to automatically try all http:// urls as https://

### ISSUE THREAD

**Issue by sdaugherty** [cwilper/http-nowhere#1]
I'd like to see an option to attempt to rewrite all URLs to https URLs, which would slightly increase the number of sites accessible with the plugin enabled, since some sites serve the same content under https as they do on http... but have all their links pointing to the unsecure version.

**Comment by cwilper** [comment]
Good idea. Targeted for next version.

**Comment by cwilper** [comment]
Added feature in version 2.1.0, tagged in github and available via Firefox Add-Ons site shortly. Requires Firefox 20.0+ as it relies on https://developer.mozilla.org/en-US/docs/XPCOM_Interface_Reference/nsIHttpChannel#redirectTo()
