### ISSUE TITLE
Typing a URL without a scheme fails

### ISSUE THREAD

**Issue by uVAdN2vUw2aMENSu19cY7ic24Gvp7Fd** [cwilper/http-nowhere#2]
When typing a url without a scheme, this attempts to browse to "http" and thus fails.

When HTTP Nowhere is turned on, the browser should assume that URLs without a scheme are HTTPS.

**Comment by cwilper** [comment]
Makes sense. Note this is somewhat related to #1, but I think this makes sense to implement as urlbar-specific behavior, and should be done unconditionally as long as the extension is enabled.

**Comment by cwilper** [comment]
Fixed in version 2.1.0, tagged in github and available via Firefox Add-Ons site shortly. Requires Firefox 20.0+ as it relies on https://developer.mozilla.org/en-US/docs/XPCOM_Interface_Reference/nsIHttpChannel#redirectTo()
